version: "3.1"
services:

    mysql:
      image: mysql:latest
      container_name: app-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=app_db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      ports:
        - "3306:3306"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: app-php
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      ports:
        - "8080:8080"

